### ISSUE TITLE
Test crashes: Console says  No valid crumb was included in request for /job/foo/doDelete. Returning 403

### ISSUE THREAD

**Issue by salimfadhley** [pycontribs/jenkinsapi#121]
Broken in Jenkins 1.519

Seems OK in Jenkins 1.480.3 (the version that comes with Ubuntu).

Getting lots of errors like this:
# 
## ERROR: test_invoke_job_parameterized (**main**.TestDownstreamUpstream)

Traceback (most recent call last):
  File "/home/sal/workspace/jenkinsapi/src/jenkinsapi_tests/systests/base.py", line 30, in setUp
    self._delete_all_jobs()
  File "/home/sal/workspace/jenkinsapi/src/jenkinsapi_tests/systests/base.py", line 39, in _delete_all_jobs
    self.jenkins.delete_job(name)
  File "/home/sal/workspace/jenkinsapi/src/jenkinsapi/jenkins.py", line 169, in delete_job
    data='some random bytes...'
  File "/home/sal/workspace/jenkinsapi/src/jenkinsapi/utils/requester.py", line 67, in post_and_confirm_status
    response.url, data, headers, response.status_code, response.text.encode('UTF-8')))
JenkinsAPIException: Operation failed. url=http://localhost:8080/job/foo/doDelete, data=some random bytes..., headers={'Content-Type': 'application/x-www-form-urlencoded'}, status=403, text=<html><head><title>Error 403</title></head><body bgcolor="#ffffff"><h1>Status Code: 403</h1>Exception: No valid crumb was included in the request<br>Stacktrace: <pre>(none)
</pre><br><hr size="1" width="90%"><i>Generated by Winstone Servlet Engine v0.9.10 at Tue Jun 18 23:39:50 BST 2013</i></body></html>

---

Ran 1 test in 0.519s

**Comment by lechat** [comment]
For visitors looking for solution:
Starting from version 0.3.2 there is a `CrumbRequester` class that handles CRSS enabled Jenkins. To use it, you need to initialize Jenkins object like this:

```
from jenkinsapi.jenkins import Jenkins
from jenkinsapit.crumb_requester import CrumbRequester

jenkins = Jenkins('http://localhost:8080', requester=CrumbRequester('http://localhost:8080'))
```

**Comment by fluffynuts** [comment]
I'd just like to chip in a sample which works in a password-protected environment, because it's not immediately clear and help(CrumbRequester) isn't particularly helpful since it just boosts arguments up to the parent Requester class. So I have a Helper which just checks on all jobs and invokes them if they last failed (sometimes we come in in the morning to find that literally a hundred jobs or more have failed because of an internet interruption, for example). The top of this file gives away the bits useful for this discussion:
```
from jenkinsapi.jenkins import Jenkins
from jenkinsapi.utils.crumb_requester import CrumbRequester

class Helper:
    def __init__(self, url, user, password):
        requester = CrumbRequester(baseurl=url, username=user, password=password)
        self._jenkins = Jenkins(baseurl=url, username=user, password=password, requester=requester)
```
Note that my import statement differes from that of @lechat -- I assume his is a typo? It took me a bit of digging to get to the CrumbRequester, so I wanted to share that too. Also note that the CrumbRequester requires all of the auth information -- perhaps it would be neater if the Jenkins constructor took an optional class instead of object since the other requesters are built with the same arguments?

**Comment by lechat** [comment]
Yes, better design would be just passing `Requester` class (and not an instance) to Jenkins and then let Jenkins object fill required fields. It is easy to implement, but it will break a lot of existing code that uses this library.

Perhaps better idea is to create shallow descendants of Jenkins class for each Requester implementation, or wrappers just like your `Helper` class.

Yeah, I will fix the typo! :)
