### ISSUE TITLE
Jobs in folders not distinguishable

### ISSUE THREAD

**Issue by vitsfr** [pycontribs/jenkinsapi#358]
While in jenkins, the job name consists of the whole path with all folders and can be referenced with this complete name e.g. when being triggered from within another job, it does not in jenkinsapi. Here job 'A/B' is referenced just as jobs['B']. This leads to problems when you have jobs with the same name in different folders.

Changes would be neccessary in jenkinsbase.py in the resolve_job_folders or process_job_folder methods to include the folder name in the job name before appending it to the result list of jobs. This way, they can be found with jobs.py's __getitem__ method using the complete name, including the folder.

For backwards compatibility and as a fallback solution it would be possible to extend the __getitem__ method to save the first job with name job_name.split('/)[-1] in a temporary variable and return it if no job with the complete name was found.

**Comment by zstyblik** [comment]
Hello,

if the proposed approach is acceptable, I would like to give it a shot. Please, let me know.

Thanks.

**Comment by lechat** [comment]
Absolutely! This is known problem for too long. I guess it is either Folders rarely used or people give up on this library once they encounter this problem/

Please send pull request.

**Comment by tgoodlet** [comment]
Any news on this guys?
It's an issue when trying to use the [pipeline multibranch plugin](https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Multibranch+Plugin) which seems to implicitly create job names under a folder.

**Comment by zstyblik** [comment]
@tgoodlet, I'm planning to give this a look over the weekend.

**Comment by tgoodlet** [comment]
@zstyblik sounds great :)

**Comment by zstyblik** [comment]
Hello,

I did give a look to the code and I felt a bit lost. And that's ok, because I'm not really familiar with the code. Then, I gave a thought to:

> For backwards compatibility and as a fallback solution it would be possible to extend the __getitem__ method to save the first job with name job_name.split('/)[-1] in a temporary variable and return it if no job with the complete name was found.

and if I understand this correctly (now) it means inconsistent results. If I have job `myfolder1/myjob` and there is no eg. `myfolder2/myjob`, then jenkinsapi would return `myjob`.
When there is `myfolder1/myjob` and  `myfolder2/myjob`, jenkinsapi would return   `myfolder1/myjob` and `myfolder2/myjob`.
This is unacceptable solution for me, and shouldn't be acceptable for anyone really, as I don't want to implement something like:

```
if `myjob` in X or `myfolder1/myjob` in X:
   # do something
```

or chase jobs around. I want consistent and reliable replies. :\ Meaning, if job is in `myfolder1`, then I expect jenkinsapi to return `myfolder1/myjob` or equivalent.

Yes, I understand backwards compatibility and all, but I really don't want to sacrifice usability and code complexity over backwards compatibility.
I meant to say that I will try to come up with workaround for my use case, but then I realized(again, maybe my understanding is wrong) that if there are eg. two jobs with the same name, jenkinsapi will return only one of them, "at random", and there is probably no way how to get all of them, to get to them etc.

Please, can somebody verify or dispute my findings?

One more thought. May be to duplicate results, resp. return `myjob` and `myfolder1/myjob` which are/will be the same job. And it's up to user to use, reference, query, the correct one. And may be that was the original idea @vitsfr had.

Thanks.

**Comment by lechat** [comment]
I think that one of the possible solutions is to implement method `cd(folder_name)` in `Jenkins` class which will return `Jenkins` instance specific for a folder. That way core functionality will stay untouched, but if you have to work with folders, then you will have to deal with them separately.

**Comment by zstyblik** [comment]
@lechat, I think I can live with that :)
