### ISSUE TITLE
Unable to get information about jobs managed via github organization (workflow/pipelines)

### ISSUE THREAD

**Issue by ssbarnea** [pycontribs/jenkinsapi#435]
I tried to get information about github organization jobs, which are exposed in the API, but I got a jenkinsapi.custom_exceptions.UnknownJob

```
    j = Jenkins(...)
    jobname = "githuborgname/job/myrepo/branch/master" 
    x = j[jobname]
    print(x)
```

GitHub organization is a core jenkins plugin since 2.0 - https://github.com/jenkinsci/pipeline-plugin

Because fixing this bug in a nice way may require changes in Jenkins here its sister issue https://issues.jenkins-ci.org/browse/JENKINS-34436

Still, we do know that even if Jenkins does not report the jobs but we know that if we add `/api/python` to the these jobs URLs it will accept API calls it means that we do still have a bug inside the python library which assumes that the job does not exist without trying its URLs.

**Comment by lechat** [comment]
Hi,

I am puzzled - in Jenkins Jira you say that such jobs don't have API, in here you say that they do. Which is it?

**Comment by lechat** [comment]
This kind of referring to job won't work because job is two folders deep: in "githuborgname" folder and then in "githubreponame" folder. But you can find job by name == branch name. 

`Jenkins` object has all jobs in flat list of job dicts, and name of job is a name of the job and not a full path to job in Jenkins hierarchy of folders. Perhaps it is a good idea to add code that will allow passing job hierarchy path to find exact job.
