### ISSUE TITLE
Got 'IndexError: list index out of range' error while getting a job

### ISSUE THREAD

**Issue by adelez** [pycontribs/jenkinsapi#474]
Hi, I'm trying to fetch a job and got this error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/jenkinsapi/jenkins.py", line 232, in __getitem__
    return self.jobs[jobname]
  File "/usr/local/lib/python2.7/dist-packages/jenkinsapi/jobs.py", line 81, in __getitem__
    return Job(None, job_name, self.jenkins)
  File "/usr/local/lib/python2.7/dist-packages/jenkinsapi/job.py", line 75, in __init__
    self.url = self._find_job_url(name)
  File "/usr/local/lib/python2.7/dist-packages/jenkinsapi/job.py", line 88, in _find_job_url
    full_job_name = search_result.json()['suggestions'][0]['name']
IndexError: list index out of range

The job name is in among the keys because if it didn't exist, it'll throw "jenkinsapi.custom_exceptions.UnknownJob" error instead. The same code works on my other jobs. Any ideas? Thanks.

**Comment by adelez** [comment]
Note that for this job that fails, display name and name are different. That's the only difference I can think of than the working jobs:
"displayName" : "gRPC pull requests",
  "displayNameOrNull" : "gRPC pull requests",
  "name" : "gRPC_pull_requests",

A good job:
"displayName" : "gRPC_interop_master",
  "displayNameOrNull" : null,
  "name" : "gRPC_interop_master",

**Comment by magjac** [comment]
I'm getting the same problem for:

  "displayName" : "smoke-Smoketest_install_punisher#1",
  "displayNameOrNull" : "smoke-Smoketest_install_punisher#1",
  "name" : "smoke-Smoketest_install_punisher-1",

Seems like the search box (used in https://github.com/pycontribs/jenkinsapi/blob/master/jenkinsapi/job.py#L81) uses the display name:

> curl 'http://ci.netinsight.se:8080/jenkins/search/suggest?query=smoke-Smoketest_install_punisher-1'; echo
{"suggestions":[]}
> curl 'http://ci.netinsight.se:8080/jenkins/search/suggest?query=smoke-Smoketest_install_punisher%231' ; echo
{"suggestions":[{"name":"smoke-Smoketest_install_punisher-1"}]}

Unfortunately I can't use the workaround, because my display name is an illegal job name.

**Comment by lechat** [comment]
See my reply on #471 

I think I will add parameter to `Jenkins.__init__` to force it to not read job urls on instances with thousands of jobs. With warning message in log when this option is selected that some jobs will not be found. 

As I said in #471: I don't know if Jenkins has better way to find out job's url by job name.

**Comment by magjac** [comment]
I haven't used folders myself, but according to https://go.cloudbees.com/docs/cloudbees-documentation/cje-user-guide/chapter-folder.html:

"Folders are namespace aware, so Job A in Folder A is logically different than Job A in Folder B"

It seems to me that a job name is not unique if you don't include the (nested) folder it is in, in it's name.

If you **do** know this, you can use it to determine the url of it directly.

If you **don't** know it, you can't use your approach of searching for the leaf name anyway, because you might get several different jobs with the same leaf name.

Do I understand you correctly, that you are going to revert to the old method as default and make the new method optional by a parameter? If so, I'll be happy with that solution (but won't use the option).

**Comment by lechat** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-37576

**Comment by lechat** [comment]
Restored old way of working with jobs. Will do PYPI release later today.

**Comment by lechat** [comment]
Released v0.30.1 with the fix.

**Comment by magjac** [comment]
Thanks @lechat. v0.3.1 works fine :-)
