### ISSUE TITLE
Interacting with Jenkins API is slow

### ISSUE THREAD

**Issue by jmreicha** [pycontribs/jenkinsapi#557]
##### ISSUE TYPE
 - Bug Report
 - How to...

##### Jenkinsapi VERSION

0.3.4

##### Jenkins VERSION

2.63

##### SUMMARY

Calling Jenkins with JenkinsAPI is slow.  It takes around 30 seconds just to authenticate to Jenkins and around 60 seconds to get a build number with the following code:

```
jenkins = Jenkins(JENKINS_URL, username=JENKINS_USER, password=JENKINS_PASS)
job = jenkins.get_job("foo")
build = job.get_last_build()
print(build)
```

My guess is that there is something going on behind the scenes that is making this so slow, just not sure what.  Maybe I'm just doing something silly.  Is there a way to enable some kind of debugging to see what is causing things to slow down?

I am using Github authentication for Jenkins but that doesn't seem to be related, I have tested building the job with Curl and it isn't as slow.

##### EXPECTED RESULTS

Expect authentication and interacting with Jenkins to be much faster.

##### ACTUAL RESULTS

As mentioned, it takes about 30 seconds to authenticate, around 50-60 seconds to kick off a build or pull a build number from a job, etc.

**Comment by harlowja** [comment]
Ya, I've seen this also, it's imho because of internal caching the library is doing (imho not for very good reasons).

**Comment by ssbarnea** [comment]
Closing as incomplete because this looks like a local configuration issue and not being something specific to the library.

**Comment by jmreicha** [comment]
It seems like the culprit is this library, it isn't slow when using Curl.  Is there a way to enable debugging to figure out exactly what is happening?

**Comment by harlowja** [comment]
Enable debug logging, u'll see that at various points this library does a bunch of 'scans' of jenkins (to fill internal caches) that it probably in all likelyhood does not need to do (or it should just fetch this information much later).

**Comment by jmreicha** [comment]
@harlowja I see, you're right.  It looks like all of my jobs are getting loaded when I create the Jenkins object.  After the initial load things seem to be much faster, I may just need to rework how I am using the library.

It still seems like there should be a way to bypass this initial scan though for cases where a user doesn't care about all of the Jenkins info, but I don't know how trivial that would be to do.

**Comment by harlowja** [comment]
Might be a bunch of work, or might not.

https://github.com/pycontribs/jenkinsapi/blob/master/jenkinsapi/jenkinsbase.py#L34-L35 (one such area).

Acutally there a lot of calls to `def poll(self):` in various parts of this library, which can trigger a bunch of data to be fetched. 

To fix all of them, there would need to be a much smarter implementation that doesn't poll all the time but only fetches things that it needs to (and caches them if it wants to).

One place is any access of https://github.com/pycontribs/jenkinsapi/blob/master/jenkinsapi/jenkins.py#L105 (the jobs property) will start to scan a lot of things. Even getting a single job (which should not fetch all jobs currently will due to https://github.com/pycontribs/jenkinsapi/blob/master/jenkinsapi/jenkins.py#L126-L132, ie this touches the previously mentioned `jobs` property which fetches all the jobs...)

So perhaps there are a lot of low hanging fruit here, and it'd be super to start getting rid of them IMHO...

**Comment by lechat** [comment]
`Jenkins._poll()` overrides `JenkinsBase._poll()` to fetch absolute minimum job info (name, status, url): https://github.com/pycontribs/jenkinsapi/blob/master/jenkinsapi/jenkins.py#L55-L58

There is an experimental branch, "get_tree", where all objects override `_poll()` to fetch minimal data. 

In my work Jenkins I have 3k+ jobs and I use code from master w/o any noticeable slowness, and code in experimental branch does not give much of speed increase. I'd appreciate if somebody, who experiences slowness, would try that branch out.

**Comment by alex-ml** [comment]
Tried the "get_tree" branch on a script that takes 10 minutes to iterate all the ~400 builds from a Jenkins job.

```
git clone https://github.com/lechat/jenkinsapi
cd jenkinsapi/
git checkout get_tree
git describe
jenkinsapi-0.1-1064-g5f1eba5
pip uninstall jenkinsapi
pip install -e .
```
```
In [1]: from jenkinsapi.jenkins import Jenkins

In [2]: jenkins = Jenkins("http://127.0.0.1:8080/jenkins")

In [3]: build = jenkins.jobs["tests"].get_last_build()
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-3-181a92efac09> in <module>()
----> 1 build = jenkins.jobs["tests"].get_last_build()

/home/alex/jenkinsapi/jenkinsapi/jobs.py in __getitem__(self, job_name)
     81             job_data = [job_row for job_row in self._data
     82                         if job_row['name'] == job_name][0]
---> 83             return Job(job_data['url'], job_data['name'], self.jenkins)
     84         else:
     85             raise UnknownJob(job_name)

/home/alex/jenkinsapi/jenkinsapi/job.py in __init__(self, url, name, jenkins_obj)
     72         }
     73         self.url = url
---> 74         super(Job, self).__init__(self.url)
     75 
     76     def __str__(self):

/home/alex/jenkinsapi/jenkinsapi/jenkinsbase.py in __init__(self, baseurl, poll)
     33         self.baseurl = self.strip_trailing_slash(baseurl)
     34         if poll:
---> 35             self.poll()
     36 
     37     def get_jenkins_obj(self):

/home/alex/jenkinsapi/jenkinsapi/job.py in poll(self, tree)
    103         data = super(Job, self).poll(tree=tree)
    104         if not tree:
--> 105             self._data = self._add_missing_builds(self._data)
    106         else:
    107             return data

/home/alex/jenkinsapi/jenkinsapi/job.py in _add_missing_builds(self, data)
    122         # do not call _buildid_for_type here: it would poll and do an infinite
    123         # loop
--> 124         oldest_loaded_build_number = data["builds"][-1]["number"]
    125         if 'firstBuild' not in self._data or not self._data['firstBuild']:
    126             first_build_number = oldest_loaded_build_number

KeyError: 'number'
```
With the "master" branch (jenkinsapi-0.1-1191-gd8d5a07): the above snippet works, get_last_build() takes ~ 1 second, and the full script (minimal example below) takes ~10 minutes.

With the job_speedup branch (jenkinsapi-0.1-1129-gafc46ae), no speed improvement was noticed.

With the official version ("pip install jenkins" - 0.3.6 under python 2.7), the script is just as slow - actually that's the reason I've tried the experimental branch.

Minimal example:
```
In [1]: from jenkinsapi.jenkins import Jenkins

In [2]: jenkins = Jenkins("http://127.0.0.1:8080/jenkins")

In [3]: ids = jenkins.jobs["tests"].get_build_ids()
(takes ~ 1 second to complete)

In [4]: for id in ids:
   ...:     print id, jenkins.jobs["tests"].get_build(id)
   ...:     
409 tests #409
408 tests #408
407 tests #407
...
(takes ~ 10 minutes to complete)
```

CPU usage while running the script: ~ 20% for ipython, ~5% for java/jenkins (htop). Idle otherwise.

Browsing the same job on the Jenkins web interface is very fast (less than 1 second to list all builds, changes and so on).

HTH
