### ISSUE TITLE
Is it support Jenkins2.x pipeline?3ks

### ISSUE THREAD

**Issue by gwenxia** [pycontribs/jenkinsapi#558]
Could you pls tell me the lastest jenkinsapi version whether support jenkins2.x pipleline?such as:
1, create/delete pipeline?
2, get pipeline exectute result?
3, get stage status, cost time etc.
By the way, could you pls tell me what is different between jenkinsapi and python-jenkins?

**Comment by ssbarnea** [comment]
As someone that had to use both libraries, I am a bit inclined to believe that `jenkinsapi` is a better bet because:
* uses `requests` library which is far superior to old urllib
* is bit better maintained
* has support for jenkins2 security features (the infamous crumbs)

I hope that I will see some convergence in the future because having two libraries is not good for maintenance and contributions.

**Comment by gwenxia** [comment]
I got it. Tks.
