### ISSUE TITLE
invoke job -> 403: No valid crumb was included in the request

### ISSUE THREAD

**Issue by zorce** [pycontribs/jenkinsapi#563]
Bug Report

jenkinsapi version 0.3.4

jenkins version 2.61

##### SUMMARY
When try to invoke a job i get the 403 return "No valid crumb was included in the request"

code:
    jenkins = Jenkins("http://jenkins.domain.com:8080/", username='username', password='pwd')
    job = jenkins['My Job Name']
    print(job.get_build_triggerurl())
    job.invoke(securitytoken='mytoken', build_params={'parameter1':'parameter','tags':'mytag'})

**Comment by ssbarnea** [comment]
You have two workaround options to make it work: either disable crumbs on your instance or to use CrumbRequester instead of normal Requester when you connect to Jenkins.

Still I do find this bug valid because I consider that this aspect should be hidden and that the library should just work the same way, regardless of the crumb configuration on the server side.

**Comment by lechat** [comment]
The problem is that crumb is required only for POSTs, so to see if CrumbRequester is required we need to POST something right away after connecting to Jenkins. That will add to overall time used to connect to Jenkins... 

And if CrumbRequester is default Requester, how do we check that crumbs are not enabled?

Perhaps better approach would be asking Jenkins settings by requesting Security page...

**Comment by Ivru** [comment]
Then at least, this should be documented...

**Comment by Leibniz137** [comment]
try this:

```python
url = ...
username = ...
password = ...
crumb_requester = CrumbRequester(
    baseurl=url,
    username=username,
    password=password
)
j = Jenkins(
    url,
    username=username,
    password=password,
    requester=crumb_requester
)
```

**Comment by lechat** [comment]
[Example code: examples/how_to/use_crumbs.py](https://github.com/pycontribs/jenkinsapi/blob/master/examples/how_to/use_crumbs.py)

**Comment by mujahid76** [comment]
i am facing
