### ISSUE TITLE
QueueItem.get_build retrieves incorrect build

### ISSUE THREAD

**Issue by gwkunze** [pycontribs/jenkinsapi#697]
##### ISSUE TYPE
Bug Report

##### SUMMARY
We use jenkinsapi to invoke a build, we get the QueueItem, wait for it to start, get the build and wait for the build to complete. However with one job, the builds were randomly reported as failing even though jenkins showed them succeeding. Diving into this show that the build doesn't in anyway match the QueueItem. I.e. QueueItem was returning a build for another job that had already completed.

###### PROBLEM
`QueueItem.get_build` effectively returns `self.jenkins[self._data['task']['name']][self._data['executable']['number']]`. But in the case you make use of Jenkins folders and you have a job with the same task name in different folders you don't necessarily get the correct one.

**Comment by lechat** [comment]
I am not sure how to fix that because there is no clear separation between folder url and job url in REST API. Before introduction of Folders plugin the job names were unique within server, with folders - it is not a case, but since folder and job have same url, it is not clear how to separate folder from job and one job from another.

I am happy to accept PR that will add support of folders.
